### PR TITLE
Profile UI fix

### LINKED ISSUE #104: UI Fix

### PR DESCRIPTION
**Pull request by alifirst01**
Adjusted profile UI
Added vertical navbar on profile page
Fixed the issue of empty date input during profile update
Included environment variable for storage bucket

Fixed #104

### CODE REVIEW

File: frontend/course-hub-ui/src/js/CHProfile.js [hunk 1]
```diff
@@ -312,90 +313,94 @@ class ProfilePage extends Component {
...
-
-                                                <Form.Group as={Col} controlId="formGridZip">
-                                                    <Form.Label>ZIP</Form.Label>
-                                                    <Form.Control className="profile-form-control" onChange={this.handleZipChange} value={this.state.zip_code} />
+                                        <Card className="profile-edit-card">
+                                            <Card.Title className="card-title">Edit Profile</Card.Title>
+                                            <Form className="profile-form" onSubmit={e => this.handleSubmit(e)}>
+                                                <Form.Row>
+                                                    <Form.Group as={Col} controlId="formGridfname">
+                                                        <Form.Label>FIRST NAME</Form.Label>
```
Comment (abhijeetkharkar) [inline frontend/course-hub-ui/src/js/CHProfile.js]: I would recommend keeping the labels to Camel Case (First Name in place of FIRST NAME) for better UX.

Comment (alifirst01) [reply frontend/course-hub-ui/src/js/CHProfile.js]: Its a kind of label input scheme I follow. Since the size of label text is small, I keep all characters in upper case.
I guess once we finalize our color scheme, we can revisit these details and make them consistent across all components.

Comment (abhijeetkharkar) [reply frontend/course-hub-ui/src/js/CHProfile.js]: Alright!! Approving
